package com.myspace.datamodel_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NestedData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public NestedData() {
    }




}